import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixture,request,login,paired,encrypted,viewerCode,adminToken,password} from './helpers.mjs';
import {wrap} from '../public/crypto.js';
test('password, persistent rate limits, CSRF, sessions and no unauthenticated content',async t=>{
 const f=await fixture();t.after(()=>f.close());
 assert.equal((await request(f,'/api/web/config')).status,401);
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password},origin:'https://evil.invalid'})).status,403);
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password:'wrong'}})).status,401);
 const session=await login(f);assert.match(session.cookie,/sv_session=/);
 const r=await request(f,'/api/web/config',session);assert.equal(r.status,200);assert.equal(r.body.wrapped,null);assert.match(r.headers.get('cache-control'),/no-store/);
 assert.equal((await request(f,'/api/web/config',{...session,csrf:'wrong',method:'POST',body:{}})).status,403);
 assert.equal((await request(f,'/api/web/config',{...session,method:'POST',body:{}})).status,400);
 await f.restart();assert.equal((await request(f,'/api/web/config',session)).status,200);
 for(let i=0;i<8;i++)await request(f,'/api/web/login',{method:'POST',body:{password:'wrong'}});
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password}})).status,429);
 await f.restart();assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password}})).status,429);
 f.advance(901);const second=await login(f);
 assert.equal((await request(f,'/api/web/logout',{...second,method:'POST',body:{}})).status,200);
 assert.equal((await request(f,'/api/web/config',second)).status,401);
 f.advance(3601);assert.equal((await request(f,'/api/web/config',session)).status,401);
});
test('v2 delivery survives ACK and restart, browser archive encrypted, roles enforced',async t=>{
 const f=await fixture();t.after(()=>f.close());const c=await paired(f),base='/api/v2/channels/'+c.channelId;
 const e=encrypted(c,'Isolated OTP 654321',f.now);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.readToken,device:c.deviceId})).status,401);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:'00000000-0000-0000-0000-000000000000'})).status,403);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:c.deviceId})).status,200);
 assert.equal((await request(f,base+'/messages',{bearer:c.writeToken})).status,401);
 assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[e]);
 assert.equal((await request(f,base+'/ack',{method:'POST',body:{ids:[e.id]},bearer:c.readToken})).status,200);
 assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[]);
 const session=await login(f),wrapped=await wrap(viewerCode(c),password);
 assert.equal((await request(f,'/api/web/config',{...session,method:'POST',body:wrapped})).status,200);
 await f.restart();assert.deepEqual((await request(f,'/api/web/config',session)).body.wrapped,wrapped);
 const archive=await request(f,'/api/web/messages',{...session,method:'POST',body:{channelId:c.channelId,readToken:c.readToken}});
 assert.deepEqual(archive.body.messages,[e]);assert.ok(!JSON.stringify(archive.body).includes('654321'));
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:c.deviceId})).body.duplicate,true);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:{...e,mac:adminToken},bearer:c.writeToken,device:c.deviceId})).status,409);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:{...e,expiresAt:e.expiresAt+1},bearer:c.writeToken,device:c.deviceId})).status,400);
 f.advance(604801);assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[]);await f.store.prune(f.now);
 assert.equal((await f.store.pool.query('SELECT count(*)::int AS n FROM sv_messages')).rows[0].n,0);
 assert.equal((await request(f,base,{method:'DELETE',bearer:c.writeToken})).status,401);
 assert.equal((await request(f,base,{method:'DELETE',bearer:c.readToken})).status,200);
 assert.equal((await request(f,base+'/messages',{bearer:c.readToken})).status,401);
});
test('pair expiry, second device refusal, bounded payload and archive pagination',async t=>{
 const f=await fixture();t.after(()=>f.close());const c=await paired(f),base='/api/v2/channels/'+c.channelId;
 assert.equal((await request(f,base+'/claim',{method:'POST',bearer:c.writeToken,body:{deviceId:'00000000-0000-0000-0000-000000000000'}})).status,409);
 const fresh=(await request(f,'/api/v2/channels',{method:'POST',body:{},bearer:adminToken})).body;f.advance(901);
 assert.equal((await request(f,'/api/v2/channels/'+fresh.channelId+'/claim',{method:'POST',bearer:fresh.writeToken,body:{deviceId:c.deviceId}})).status,410);
 assert.equal((await request(f,base+'/messages?token=bad',{bearer:c.readToken})).status,400);
 assert.equal((await request(f,base+'/messages',{method:'POST',bearer:c.writeToken,device:c.deviceId,body:{blob:'x'.repeat(50000)}})).status,413);
 for(let i=0;i<102;i++)await f.store.put(c.channelId,c.writeToken,c.deviceId,encrypted(c,'test '+i,f.now),f.now);
 const page=await f.store.list(c.channelId,c.readToken,f.now,true);assert.equal(page.messages.length,100);assert.ok(page.nextCursor);
 const older=await f.store.list(c.channelId,c.readToken,f.now,true,page.nextCursor);assert.equal(older.messages.length,2);assert.equal(older.nextCursor,null);assert.equal(new Set([...page.messages,...older.messages].map(x=>x.id)).size,102);
});
