import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixture,request,login,paired,encrypted,viewerCode,adminToken,password,registration} from './helpers.mjs';
import {wrap,unwrap} from '../public/crypto.js';
import {databaseFromEnvironment,verifiedDatabaseURL,startupFailureCode} from '../lib/config.mjs';
import {createApp} from '../server.mjs';
test('dedicated Neon prefix takes precedence; remote Postgres always verifies TLS',()=>{
 const dedicated='postgresql://example.neon.tech/app?sslmode=require&channel_binding=require&uselibpqcompat=true';
 assert.equal(databaseFromEnvironment({SV_MSG_DATABASE_URL:dedicated,DATABASE_URL:'previous-value'}),dedicated);
 assert.equal(databaseFromEnvironment({SV_MSG_DATABASE_URL:' ',DATABASE_URL:dedicated}),dedicated);
 assert.throws(()=>databaseFromEnvironment({}));assert.throws(()=>verifiedDatabaseURL('invalid'));assert.throws(()=>verifiedDatabaseURL('https://example.invalid/'));
 const parsed=new URL(verifiedDatabaseURL(dedicated));assert.equal(parsed.searchParams.get('sslmode'),'verify-full');assert.equal(parsed.searchParams.get('channel_binding'),'require');assert.equal(parsed.searchParams.has('uselibpqcompat'),false);
 assert.equal(new URL(verifiedDatabaseURL('postgresql://127.0.0.1/test')).searchParams.has('sslmode'),false);
});
test('startup validates configuration and diagnostics never log exception secrets',()=>{
 assert.throws(()=>createApp({adminToken:'incorrect'}),/invalid_relay_admin_token/);
 assert.throws(()=>createApp({adminToken,passwordHash:'incorrect'}),/invalid_web_password_hash/);
 assert.equal(startupFailureCode(new Error('postgresql://user:private-test-value@example.invalid/db')),'database_or_runtime_unavailable');
 assert.equal(startupFailureCode(Object.assign(new Error('private-test-value'),{code:'28P01'})),'28P01');
 assert.equal(startupFailureCode(Object.assign(new Error('private-test-value'),{code:'includes a secret'})),'database_or_runtime_unavailable');
 assert.equal(startupFailureCode(new Error('invalid_public_origin')),'invalid_public_origin');
});
test('password registration discovers separate encrypted device chats; retries and migration preserve existing data',async t=>{
 const f=await fixture();t.after(()=>f.close());const legacy=await paired(f),session=await login(f);
 const legacyWrapped=await wrap(viewerCode(legacy),password);await f.store.saveConfig(legacyWrapped);
 const a=await registration(f,'iPhone A <img onerror=alert(1)>'),b=await registration(f,'iPhone B');
 assert.equal((await request(f,'/api/web/devices')).status,401);
 assert.equal((await request(f,'/api/native/devices',{bearer:adminToken})).status,401);
 assert.equal((await request(f,'/api/native/register',{method:'POST',body:{...a.body,password:'wrong'},origin:undefined})).status,401);
 assert.equal((await request(f,'/api/native/register',{method:'POST',body:a.body,origin:'https://evil.invalid'})).status,403);
 for(const d of [a,b])assert.equal((await request(f,'/api/native/register',{method:'POST',body:d.body,origin:null})).status,201);
 assert.equal((await request(f,'/api/native/register',{method:'POST',body:a.body,origin:null})).status,201);
 assert.equal((await request(f,'/api/native/register',{method:'POST',body:{...a.body,channelId:b.c.channelId},origin:null})).status,409);
 assert.equal((await f.store.pool.query('SELECT count(*)::int AS n FROM sv_channels')).rows[0].n,3);
 for(const [d,text]of [[a,'A only 123456'],[b,'B only 654321']])await f.store.put(d.c.channelId,d.c.writeToken,d.c.deviceId,encrypted(d.c,text,f.now),f.now);
 const devices=(await request(f,'/api/web/devices',session)).body.devices;assert.equal(devices.length,2);
 for(const d of devices){const v=await unwrap(d.wrapped,password,f.origin);assert.equal(v.channelId,d.channelId);assert.equal('writeToken'in v,false);assert.ok(!JSON.stringify(d).includes(v.readToken));await assert.rejects(()=>unwrap(d.wrapped,'wrong',f.origin));}
 const result=await request(f,'/api/native/login',{method:'POST',body:{password},origin:null});assert.equal(result.status,200);
 assert.equal((await request(f,'/api/native/devices',{bearer:result.body.token})).body.devices.length,2);
 await f.restart();assert.deepEqual(await f.store.config(),legacyWrapped);assert.equal((await f.store.devices()).length,2);
 const archive=await request(f,'/api/web/messages',{...session,method:'POST',body:{channelId:a.c.channelId,readToken:b.c.readToken}});assert.equal(archive.status,401);
 assert.equal((await f.store.list(a.c.channelId,a.c.readToken,f.now,true)).messages.length,1);
 f.advance(3601);assert.equal((await request(f,'/api/native/devices',{bearer:result.body.token})).status,401);
});
test('password, persistent rate limits, CSRF, sessions and no unauthenticated content',async t=>{
 const f=await fixture();t.after(()=>f.close());
 assert.equal((await request(f,'/api/web/config')).status,401);
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password},origin:'https://evil.invalid'})).status,403);
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password:'wrong'}})).status,401);
 const session=await login(f);assert.match(session.cookie,/sv_session=/);
 const r=await request(f,'/api/web/config',session);assert.equal(r.status,200);assert.equal(r.body.wrapped,null);assert.match(r.headers.get('cache-control'),/no-store/);
 assert.equal((await request(f,'/api/web/config',{...session,csrf:'wrong',method:'POST',body:{}})).status,403);
 assert.equal((await request(f,'/api/web/config',{...session,method:'POST',body:{}})).status,400);
 await f.restart();assert.equal((await request(f,'/api/web/config',session)).status,200);
 for(let i=0;i<8;i++)await request(f,'/api/web/login',{method:'POST',body:{password:'wrong'}});
 assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password}})).status,429);
 await f.restart();assert.equal((await request(f,'/api/web/login',{method:'POST',body:{password}})).status,429);
 f.advance(901);const second=await login(f);
 assert.equal((await request(f,'/api/web/logout',{...second,method:'POST',body:{}})).status,200);
 assert.equal((await request(f,'/api/web/config',second)).status,401);
 f.advance(3601);assert.equal((await request(f,'/api/web/config',session)).status,401);
});
test('web QR creates a password-wrapped reader; one claim remains valid after QR expiry and restart',async t=>{
 const f=await fixture();t.after(()=>f.close());const legacy=await paired(f),legacyCipher=encrypted(legacy,'Preserve legacy',f.now);await f.store.put(legacy.channelId,legacy.writeToken,legacy.deviceId,legacyCipher,f.now);
 const session=await login(f),a=await registration(f,'QR iPhone'),b=await registration(f,'QR iPhone B');
 const body=({body:{password,deviceId,...v}})=>v;
 assert.equal((await request(f,'/api/web/pair',{method:'POST',body:body(a)})).status,401);
 assert.equal((await request(f,'/api/web/pair',{...session,csrf:'wrong',method:'POST',body:body(a)})).status,403);
 const r=await request(f,'/api/web/pair',{...session,method:'POST',body:body(a)});assert.equal(r.status,201);
 assert.deepEqual((await request(f,'/api/web/pair',{...session,method:'POST',body:body(a)})).body,r.body);
 assert.equal((await f.store.devices()).length,0);
 const claim=d=>request(f,'/api/v2/channels/'+d.c.channelId+'/claim',{method:'POST',bearer:d.c.writeToken,body:{deviceId:d.c.deviceId}});
 assert.equal((await claim(a)).status,200);assert.equal((await f.store.devices()).length,1);
 assert.deepEqual(await unwrap((await f.store.devices())[0].wrapped,password,f.origin),viewerCode(a.c));
 await request(f,'/api/web/pair',{...session,method:'POST',body:body(b)});f.advance(901);
 assert.equal((await claim(b)).status,410);assert.equal((await claim(a)).status,200);
 assert.equal((await request(f,'/api/v2/channels/'+a.c.channelId+'/claim',{method:'POST',bearer:a.c.writeToken,body:{deviceId:b.c.deviceId}})).status,409);
 await f.restart();assert.equal((await claim(a)).status,200);await f.store.prune(f.now);
 assert.equal((await f.store.devices()).length,1);assert.equal((await f.store.list(legacy.channelId,legacy.readToken,f.now,true)).messages.length,1);
 const e=encrypted(a.c,'Still connected after QR expired',f.now);assert.equal((await request(f,'/api/v2/channels/'+a.c.channelId+'/messages',{method:'POST',bearer:a.c.writeToken,device:a.c.deviceId,body:e})).status,200);
 assert.equal((await f.store.list(a.c.channelId,a.c.readToken,f.now,true)).messages.length,1);
});
test('v2 delivery survives ACK and restart, browser archive encrypted, roles enforced',async t=>{
 const f=await fixture();t.after(()=>f.close());const c=await paired(f),base='/api/v2/channels/'+c.channelId;
 const e=encrypted(c,'Isolated OTP 654321',f.now);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.readToken,device:c.deviceId})).status,401);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:'00000000-0000-0000-0000-000000000000'})).status,403);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:c.deviceId})).status,200);
 assert.equal((await request(f,base+'/messages',{bearer:c.writeToken})).status,401);
 assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[e]);
 assert.equal((await request(f,base+'/ack',{method:'POST',body:{ids:[e.id]},bearer:c.readToken})).status,200);
 assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[]);
 const session=await login(f),wrapped=await wrap(viewerCode(c),password);
 assert.equal((await request(f,'/api/web/config',{...session,method:'POST',body:wrapped})).status,200);
 await f.restart();assert.deepEqual((await request(f,'/api/web/config',session)).body.wrapped,wrapped);
 const archive=await request(f,'/api/web/messages',{...session,method:'POST',body:{channelId:c.channelId,readToken:c.readToken}});
 assert.deepEqual(archive.body.messages,[e]);assert.ok(!JSON.stringify(archive.body).includes('654321'));
 assert.equal((await request(f,base+'/messages',{method:'POST',body:e,bearer:c.writeToken,device:c.deviceId})).body.duplicate,true);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:{...e,mac:adminToken},bearer:c.writeToken,device:c.deviceId})).status,409);
 assert.equal((await request(f,base+'/messages',{method:'POST',body:{...e,expiresAt:e.expiresAt+1},bearer:c.writeToken,device:c.deviceId})).status,400);
 f.advance(604801);assert.deepEqual((await request(f,base+'/messages',{bearer:c.readToken})).body.messages,[]);await f.store.prune(f.now);
 assert.equal((await f.store.pool.query('SELECT count(*)::int AS n FROM sv_messages')).rows[0].n,0);
 assert.equal((await request(f,base,{method:'DELETE',bearer:c.writeToken})).status,401);
 assert.equal((await request(f,base,{method:'DELETE',bearer:c.readToken})).status,200);
 assert.equal((await request(f,base+'/messages',{bearer:c.readToken})).status,401);
});
test('pair expiry, second device refusal, bounded payload and archive pagination',async t=>{
 const f=await fixture();t.after(()=>f.close());const c=await paired(f),base='/api/v2/channels/'+c.channelId;
 assert.equal((await request(f,base+'/claim',{method:'POST',bearer:c.writeToken,body:{deviceId:'00000000-0000-0000-0000-000000000000'}})).status,409);
 const fresh=(await request(f,'/api/v2/channels',{method:'POST',body:{},bearer:adminToken})).body;f.advance(901);
 assert.equal((await request(f,'/api/v2/channels/'+fresh.channelId+'/claim',{method:'POST',bearer:fresh.writeToken,body:{deviceId:c.deviceId}})).status,410);
 assert.equal((await request(f,base+'/messages?token=bad',{bearer:c.readToken})).status,400);
 assert.equal((await request(f,base+'/messages',{method:'POST',bearer:c.writeToken,device:c.deviceId,body:{blob:'x'.repeat(50000)}})).status,413);
 for(let i=0;i<102;i++)await f.store.put(c.channelId,c.writeToken,c.deviceId,encrypted(c,'test '+i,f.now),f.now);
 const page=await f.store.list(c.channelId,c.readToken,f.now,true);assert.equal(page.messages.length,100);assert.ok(page.nextCursor);
 const older=await f.store.list(c.channelId,c.readToken,f.now,true,page.nextCursor);assert.equal(older.messages.length,2);assert.equal(older.nextCursor,null);assert.equal(new Set([...page.messages,...older.messages].map(x=>x.id)).size,102);
});
